Swapped to using defconfig, cleaned up the linux PKGBUILD, added it as a normal dep

diff --git a/packages/linux/PKGBUILD b/packages/linux/PKGBUILD
--- a/packages/linux/PKGBUILD
+++ b/packages/linux/PKGBUILD
@@ -1,16 +1,11 @@
 # Maintainer: Alastair Hughes < hobbitalastair at yandex dot com>
 
-# Based of the Arch Linux linux package
-
-# Edit this line to change the target config (TODO: Make automatic)
-_target_config='qemu-malta'
-
 # Package information
-pkgname="linux-${_target_config}"
-_major_version='4.0'
+pkgname="linux"
+_major_version='4.4'
 _srcname="linux-${_major_version}"
-pkgdesc="Linux kernel and modules for '${_target_config}'"
-pkgver="${_major_version}.1"
+pkgdesc="defconfig kernel"
+pkgver="${_major_version}.5"
 pkgrel=1
 
 # Additional information...
@@ -20,58 +15,42 @@ license=('GPL2')
 
 # Dependency information
 groups=('base')
-#TODO: Expand!
+# Depends: toolchain/gcc-static toolchain/binutils
+# HostDepends: bc inetutils
+# TODO: Expand and update!
 makedepends=('bc' 'gcc')
-provides=('kernel')
-conflicts=('kernel')
 
 # Building information
 options=('!strip')
-source=("https://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
-        "https://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
-        "config.${_target_config}"
-        *.patch
-       )
-md5sums=('d3fc8316d4d4d04b65cbc2d70799e763'
-         '2f2822cf2d84a8ec3a8b044e732cf45b'
-         'SKIP'
-         'ee9e4d173c2fff74659c862479570d36')
+source=("https://www.kernel.org/pub/linux/kernel/v4.x/${_srcname}.tar.xz"
+        "https://www.kernel.org/pub/linux/kernel/v4.x/patch-${pkgver}.xz")
+md5sums=('9a78fa2eb6c68ca5a40ed5af08142599'
+         'edddb33405ea1ab02b90eb9cecaa43f6')
+
+modules() {
+    # true if modules are enabled, false otherwise
+    grep ".config" -e 'CONFIG_MODULES=y' > /dev/null
+    return "$?"
+}
 
 prepare() {
     cd "${srcdir}/${_srcname}"
 
-    # Add upstream patch
+    # Add upstream patch.
     patch -p1 -i "${srcdir}/patch-${pkgver}"
 
-    # Add all of the patches
-    for _patch in ${srcdir}/*.patch; do
-        patch -p1 -i "${_patch}"
-    done
-
-    # Set extraversion to pkgrel
+    # Set extraversion to pkgrel.
     sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
 
-    # Clean up the kernel tree
+    # Clean up the kernel tree.
     make mrproper
 
-    # Update the config to use the proper toolchain!
-    sed -i -e "/CONFIG_CROSS_COMPILE/s:=\".*\":=\"${CROSS_COMPILE}\":" \
+    # Update the config to use the proper toolchain.
+    sed -i -e "/CONFIG_CROSS_COMPILE/s:=\".*\":=\"${_target_triplet}-\":" \
         "${srcdir}/config.${_target_config}"
 
-    # Move the configuration file to it's location
-    cat "${srcdir}/config.${_target_config}" > ./.config
-
-    # Make the default config
-    #make defconfig ARCH="${_target_arch_alias}" CROSS_COMPILE="${CROSS_COMPILE}"
-    # Make allnoconfig
-    #make allnoconfig ARCH="${_target_arch_alias}"
-    # Make menuconfig
-    #make menuconfig ARCH="${_target_arch_alias}" && \
-    #    exit 1
-    make menuconfig ARCH="${_target_arch_alias}"
-
-    # Update the config
-    yes "" | make oldconfig ARCH="${_target_arch_alias}"  
+    # Make the default config.
+    make defconfig ARCH="${_target_arch_alias}"
 }
 
 
@@ -79,49 +58,38 @@ build() {
     cd "${srcdir}/${_srcname}"
 
     # Make the kernel image and modules, if needed
-    if [ $(cat "${srcdir}/config.${_target_config}" | grep 'CONFIG_MODULES=y') ]
-        then
+    targets="bzImage"
+    if modules; then
         # Modules are enabled
-        #make ${MAKEFLAGS} bzImage modules ARCH="${_target_arch_alias}"
-        LDFLAGS="-rpath /sysroot/usr/lib" \
-        make V=1 ${MAKEFLAGS} ARCH="${_target_arch_alias}" CROSS_COMPILE="${CROSS_COMPILE}"
-    else
-        # Modules are not enabled
-        #make ${MAKEFLAGS} bzImage ARCH="${_target_arch_alias}"
-        LDFLAGS="-rpath /sysroot/usr/lib" \
-        make V=1 ${MAKEFLAGS} ARCH="${_target_arch_alias}" CROSS_COMPILE="${CROSS_COMPILE}"
+        targets+=" modules"
     fi
+
+    make ${MAKEFLAGS} ${targets} ARCH="${_target_arch_alias}"
 }
 
 
 package() {
     # Main Linux kernel package
-
     cd "${srcdir}/${_srcname}"
-
-    # Check for module support
-    [ $(cat "${srcdir}/config.${_target_config}" | grep 'CONFIG_MODULES=y') ] && \
-        MODULES=true || MODULES=false
 
     # Find the kernel version
     _kernver="$(make kernelrelease)"
 
-    # Make the installation directories
-    mkdir -p "${pkgdir}"/{/usr/lib/modules,/usr/lib/firmware,boot}
+    # Make the boot directory
+    mkdir -p "${pkgdir}/boot"
 
     # Copy the image to the end location
     cp "arch/${_target_arch_alias}/boot/bzImage" \
        "${pkgdir}/boot/vmlinuz-${_target_config}"
 
     # Install the modules and firmware, if required
-    if ${MODULES}; then
+    if modules; then
+        mkdir -p "${pkgdir}"/{/usr/lib/modules,/usr/lib/firmware}
         make INSTALL_MOD_PATH="${pkgdir}/" modules_install
-        # Clean up kernel source tree
+        # Remove the kernel source tree
         rm -f "${pkgdir}/lib/modules/${_kernver}"/{source,build}
         # Add vmlinux
         install -D -m644 'vmlinux' \
             "${pkgdir}/usr/lib/modules/${_kernver}/build/vmlinux" 
     fi
-
 }
-
